---
title: "Erm... What the fish???"
output: html_notebook
---

# Worcester Election Data
This project uses data from [City of Worcester Open GIS.](https://gisdata.worcesterma.gov/) 

This Notebook is used for voting  data. 

```{r}
library(sf)    # here we tell R that we need the Simple Features library (sf)
library(tmap)    # for static and interactive maps
library(leaflet) # for interactive maps
library(ggplot2) # tidyverse data visualization package
```


```{r}
#then we create an object called "precs," which is short for precincts and fill it with the data from our geojson file
precs = read_sf("data/Voting_Precincts_Based_on_2020_Census_Data.geojson")

#the "head" function tells us what is in the object and what kind of object it is
head(precs)

#let's plot our object
tm_shape(precs) +  tm_fill()

#now let's try it with some borders
tm_shape(precs) + 
  tm_fill() + 
  tm_borders()

#what about some labels?
tm_shape(precs) + 
  tm_fill(col= "forestgreen") +
  tm_borders() +  
  tm_text("Ward_Precinct", size = "AREA", col = "darkmagenta")

#that didn't work? how do we learn more about our tm_* (tmap) functions?
?tmap

#R will let you make a map object and reuse it
woo_map1 = tm_shape(precs) + 
  tm_fill(col= "forestgreen") +
  tm_borders() +  
  tm_text("Ward_Precinct", size = "AREA", col = "magenta")
```
# Polling Stations 
Your task is to make a new section that imports the voting polling stations and places them on a map.
```{r}
polls= read_sf("data/Polling_Locations.geojson")

woo_map2= tm_shape(polls) + tm_symbols(size= .8)

woo_map1+woo_map2


 


```

# Election Results 

```{r}
library(dplyr)
results = read.csv("data/worc_23_election_atlarge.csv")
head(results)
```
#joining

```{r}
prec_results = left_join(precs, results, by=c ("Ward_Precinct"="ward"))
head (prec_results)
```
#making a map

```{r}
tm_shape(prec_results) + tm_polygons("creamer")

```
#candidate names
```{r}
candidates = colnames(prec_results[8:19])
mapz = list() 
breakz = c(0,400, 600)
for (i in candidates[1:12]){
  


  themap= tm_shape(prec_results) + tm_polygons(i, breaks = breakz) + tm_layout(legend.outside = TRUE)
  mapz<-append(mapz, list(themap))
}

tmap_arrange(mapz, ncol=4)
```


